//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOOT.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHIHCC_SHOOTEntities : DbContext
    {
        public CHIHCC_SHOOTEntities()
            : base("name=CHIHCC_SHOOTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bis_Coupon> Bis_Coupon { get; set; }
        public virtual DbSet<Bis_Gift> Bis_Gift { get; set; }
        public virtual DbSet<Bis_GiftGood> Bis_GiftGood { get; set; }
        public virtual DbSet<Bis_Goods> Bis_Goods { get; set; }
        public virtual DbSet<Bis_Record> Bis_Record { get; set; }
        public virtual DbSet<Bis_RecordDetail> Bis_RecordDetail { get; set; }
        public virtual DbSet<Bis_UserRank> Bis_UserRank { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Sys_UserAccount> Sys_UserAccount { get; set; }
    }
}
