//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOOT.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string IdCard { get; set; }
        public string TelePhone { get; set; }
        public string Password { get; set; }
        public string WeiXin_Openid { get; set; }
        public string QQ_Openid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsSuper { get; set; }
    }
}
